openapi: 3.0.0
info:
  title: Sales API
  description: API for managing and analyzing sales data.
  version: 1.0.0
servers:
  - url: http://{tenant}.localhost:8000
    description: Development server with dynamic tenant name
    variables:
      tenant:
        default: abc
        description: The name of the tenant to specify the environment.

paths:
  /api/sales/top_months/:
    get:
      summary: Get Top 3 Months with Maximum Average Sales
      operationId: getTopMonths
      parameters:
        - name: tenant
          in: query
          required: false
          schema:
            type: string
            example: abc
      responses:
        '200':
          description: Top 3 months with maximum average sales
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        month:
                          type: string
                          format: date
                          example: '2024-07'
                        avg_sales:
                          type: number
                          format: float
                          example: 371.47
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: 'Unexpected error message'
  /api/sales/trends/:
    post:
      summary: Get Sales Trends for a Product
      operationId: getSalesTrends
      parameters:
        - name: tenant
          in: query
          required: false
          schema:
            type: string
            example: abc
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                  example: 1
                start_date:
                  type: string
                  format: date
                  example: '2024-01-01'
                end_date:
                  type: string
                  format: date
                  example: '2024-07-01'
      responses:
        '200':
          description: Sales trends for the product
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        total_sales:
                          type: number
                          format: float
                          example: 620.0
        '400':
          description: Bad request, missing or invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: 'Missing required parameters or invalid data'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: 'Unexpected error message'
  /api/sales/max_sales_customer/:
    get:
      summary: Find Customer with Maximum Sales per Month
      operationId: getMaxSalesCustomer
      parameters:
        - name: tenant
          in: query
          required: false
          schema:
            type: string
            example: abc
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
            example: '2024-01'
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
            example: '2024-07'
      responses:
        '200':
          description: Customer with maximum sales per month
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        customer_id:
                          type: integer
                          example: 5
                        total_sales:
                          type: number
                          format: float
                          example: 650.0
        '400':
          description: Bad request, missing or invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: 'Missing required parameters or invalid date format'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: 'Unexpected error message'
